### ISSUE TITLE
Error: Unable to resolve action. Repository not found: column-street/fastapi-openapi-specs-action

### ISSUE THREAD

**Issue by zarifaziz** [column-st/fastapi-openapi-specs-action#4]
This is my current `generate-openapi.yaml` workflow

```
name: Generate OpenAPI Spec

on:
  push:
    branches:
      - DS-1603/add-openapi-spec
    paths-ignore: ['.github/**', 'docs/**', 'manifests/**', 'README.md']

jobs:
  generate_openapi:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate OpenAPI file
        uses: column-street/fastapi-openapi-specs-action@v1.0.0
        with:
          moduleDir: src
          fileName: main.py
          appName: app
          fastapiVersioning: v1
```

But getting this error:
```
Error: Unable to resolve action. Repository not found: column-street/fastapi-openapi-specs-action
```

Is there something I'm doing wrong? Thanks.
